#import * from "./FinancialYearFragment.gql"
#import * from "./BranchEmployeeFragment.gql"
#import * from "./OrderFragment.gql"

fragment AnnualBranchEmployeeFragment on AnnualBranchEmployee {
  id
  BranchEmployee {
    ...BranchEmployeeFragment
  }
  orders {
    ...OrderFragment
  }
  FinancialYear {
    ...FinancialYearFragment
  }
}
