#import * from "./ProductFragment.gql"
#import * from "./AnnualClientFragment.gql"
#import * from "./AnnualBranchEmployeeFragment.gql"

fragment CartFragment on Cart {
  id
  orderDate
  qtty
  pdtCost
  salesPrice
}
