#import from "../fragments/BranchFragment.gql"

query AllBranches {
  branches {
    ...BranchFragment
  }
}

query SingleBranch($where: BranchWhereUniqueInput!) {
  branch(where: $where) {
    ...BranchFragment
  }
}

# query SingleBranchById($where: BranchWhereUniqueInput!) {
#   branchById(where: $where) {
#     ...BranchFragment
#   }
# }

query SingleBranchByBranchCode($branchCode: String!) {
  branchByBranchCode(branchCode: $branchCode) {
    ...BranchFragment
  }
}
