#import from "../fragments/ReportTypeFragment.gql"

query AllReportTypes {
  reportTypes {
    ...ReportTypeFragment
  }
}

query SingleReportType($id: String!) {
  reportType(id: $id) {
    ...ReportTypeFragment
  }
}
