#import from "../fragments/SessionFragment.gql"
#import from "../fragments/RegistrationFragment.gql"

query AllSessions {
  sessions {
    ...SessionFragment
    # registrations {
    #   ...RegistrationFragment
    # }
  }
}
